language: swift
osx_image: xcode11.3
env:
  global:
    - FRAMEWORK_NAME=BeeKit
    - SCAN_SCHEME=BeeKit
before_install:
  - brew outdated carthage || brew upgrade carthage
# before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  #- carthage bootstrap
script:
  - fastlane run run_tests
  - carthage build --no-skip-current
  - pod lib lint
before_deploy:
  - brew outdated carthage || brew upgrade carthage
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  skip_cleanup: true
  provider: script
  script: fastlane release_candidate
  on:
    tags: true
    all_branches: true
after_deploy:
  - fastlane github_after_deploy