# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release_candidate do |options|
    if options[:tag_name]
      git_tag_name = options[:tag_name]
    elsif ENV["TRAVIS_TAG"]
      git_tag_name = ENV['TRAVIS_TAG']
    else
      raise "provided your tag.!".red
    end

    if options[:last_tag]
      last_tag = options[:last_tag]
    else
      last_tag = last_git_tag(pattern: "*.?")
      last_tag = last_tag ? last_tag : "master"
    end
    history_log = changelog_from_git_commits(
      between: ["7ff26be", "HEAD"],  # Optional, lets you specify a revision/tag range between which to collect commit info
      pretty: "- %s %h",# Optional, lets you provide a custom format to apply to each commit when generating the changelog text
      date_format: "short",# Optional, lets you provide an additional date format to dates within the pretty-formatted string
      match_lightweight_tag: true,  # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
    )
    release_note =  ((File.read("CHANGELOG.md") rescue "No changelog provided\n") + "# Detail Commit\n" + history_log)
    github_release = set_github_release(
      repository_name: ENV["TRAVIS_REPO_SLUG"],
      name: "#{git_tag_name}",
      tag_name: git_tag_name,
      is_prerelease: true,
      description: release_note,
      upload_assets: ["BeeKit.framework.zip"]
    )
  end
  
  desc "github_after_deploy"
  lane :github_after_deploy do |options|
    if ENV["TRAVIS_TAG"]
      version_bump_podspec(version_number: ENV["TRAVIS_TAG"])
    end
    if ENV["POD_PR_REPO"]
      pod_push(repo: ENV["POD_PR_REPO"])
    end
    if ENV["ENABLE_TRUNK"]
      pod_push
    end
  end

  desc "prepare_release munual"
  desc "####Options"
  desc " * **`version`** (required): The new version of the framework"
  lane :prepare_release do |options|
    if !options[:version]
      raise "No version specified!".red
    end
    ensure_git_status_clean
    version_bump_podspec(
      version_number: options[:version]
    )
    increment_version_number(
      version_number: options[:version] # Set a specific version number
    )
    # commit the branch
    git_commit(
      path: ".",
      message: "Preparing for the #{options[:version]} release"
    )
  end
end
